title: "closure"
url: "http://closure.github.com"
author: "Ritchie Martori"
email: ""
description: "JavaScript Blog"

auto: false
source: .
paginate: 5
paginate_files:
 - index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
